App.tsx, package.json, pnpm-lock.yaml, src/components/Home/index.tsx, src/components/Settings/index.tsx, src/screens/HomeScreen.tsx, src/screens/SettingsScreen.tsx, tsconfig.json
Sets up tab navigation so that everyone else can begin work
#7
=> feat: Set up tab navigation

.eslintrc.js, .github/workflows/pr.yml, App.tsx, package.json, pnpm-lock.yaml, src/components/Home/index.tsx, src/screens/HomeScreen.tsx
Adds linting and formatting. Also revamps the README
#6
=> feat: Add linting and formatting

.gitignore, App.tsx, babel.config.js, firebaseConfig.ts, metro.config.js, package.json, pnpm-lock.yaml, src/components/Login/index.tsx, src/components/SignUp/index.tsx, src/hooks/useUser.ts, src/screens/LoginScreen.tsx, src/screens/SignUpScreen.tsx, tsconfig.json
Add Firebase configurations to expo app and create simple login/signup pages with Firebase Auth
#16 
#18
=> feat: Connect expo app to Firebase and Firebase Auth

App.tsx
Adds icons to home and settings page
#7
=> feat: Add icons for home and settings page

sprint1/rpate112.commits.txt, sprint1/rpate112.md
=> feat: Add Sprint 1 reflection

sprint1/spaladu1.commits.txt, sprint1/spaladu1.md
=> feat: Complete sprint 1 reflection

sprint1/ahuang16.commits.txt, sprint1/ahuang16.md
=> docs: add sprint 1 md and commits

src/components/Habits/HabitForm.tsx, src/components/Habits/HabitProvider.tsx
Connect habit tab to firebase
#37
=> feat: Connect habit form to Firestore

App.tsx, src/components/Home/index.tsx
Changed linear gradient colors for background, fetched sunrise and sunset data from backend, and formatted text on screen
#43
=> feat: Data fetch for homepage and formatting

src/components/Home/index.tsx, src/components/SignUp/index.tsx
Designed the sign up page on Figma, implemented the sign up page, and made edits to the color of the activity indicator on the homepage
#45
=> feat: Implement design on sign up page and edits to homepage

App.tsx, package.json, pnpm-lock.yaml, src/components/History/index.tsx, src/screens/HistoryScreen.tsx, src/types/index.ts
=> feat: Create history tab and read data from firestore

src/components/Profile/AuthorizedProfile.tsx
Profile page is now just missing displayName connection to backend and edit functionality
#46
=> feat: style profile page and add functionality to buttons 

sprint_reflections/sprint2/spaladu1.commits.txt, sprint_reflections/sprint2/spaladu1.md
=> feat: Complete sprint 2 reflection

sprint_reflections/sprint2/tpatel25.commits.txt, sprint_reflections/sprint2/tpatel25.md
=> feat: Sprint 2 reflection

lambdas/exampleMailgunTest.js, lambdas/getSunriseSunset.mjs, lambdas/sendEmail.mjs
- Created a basic Mailgun email and verified working
- Created a basic template email lambda that will take in generic arguments to send all future emails
- Fixed small sunrise/sunset lambda issue
#41 #42
=> feat: Kaylee generic email lambda

lambdas/sendDailyEmail.mjs
Call sendEmail function to schedule daily email updates
#63
=> feat: Send daily email at noon the next day

sprint_reflections/sprint2/kbae1.commits.txt, sprint_reflections/sprint2/kbae1.md
=> docs: Add sprint completed items

sprint_reflections/sprint2/ahuang16.commits.txt, sprint_reflections/sprint2/ahuang16.md
=> feat: amy sprint2 reflection

.eslintrc.js, .github/workflows/pr.yml, App.tsx, README.md, package.json, pnpm-lock.yaml, src/components/Habits/HabitForm.tsx, src/components/Habits/HabitList.tsx, src/components/Habits/HabitProvider.tsx, src/components/Habits/index.tsx, src/components/History/index.tsx, src/components/Home/index.tsx, src/components/LogIn/index.tsx, src/components/Profile/AuthorizedProfile.tsx, src/components/Profile/index.tsx, src/components/SignUp/index.tsx, src/hooks/useHabit.ts, src/hooks/useUser.ts, src/server/habits.ts, src/server/histories.tsx, src/server/index.ts, src/server/users.ts, src/types/index.ts, src/utils/getLocationFromDevice.ts
Fix useUser and add loading screens to all pages
Add import sorting
Update README to prepare for final assignment submission
Extract database functions to own folder
Remove reference to push notifications
#66 
#92 
#93 
#97
=> feat: Refactor server functions, update README, and add import sorting

src/components/Profile/AuthorizedProfile.tsx
Restyled authorized profile page to be similar to login/signup pages
"Reset Location" button should now actually update the database
#76 #90
=> feat: restyled and added reset location functionality to profile page

src/components/Home/index.tsx, src/components/SignUp/index.tsx
Updated the homepage to account for the user's lat and long if signed in, and device's location if signed out. Updated the homepage's greeting message. Updated the Sign Up page's Username block to Display Name. 
#67
=> feat: Update homepage to care about auth

.eslintrc.js, src/components/Habits/AddHabitForm.tsx, src/components/Habits/EditHabitForm.tsx, src/components/Habits/HabitList.tsx, src/components/Habits/HabitProvider.tsx, src/components/Habits/index.tsx, src/server/habits.ts
Changes HabitForm to AddHabitForm
Adds EditHabitForm
#75
=> feat: Add Edit Habit Form

lambdas/exampleMailgunTest.js, src/components/Home/index.tsx
Changed POST request to a GET request by passing in query parameters. Created a new function in AWS lambda. Changed .env file
#88
=> feat: Change URL to a get request paassing in query parameters

lambdas/exampleMailgunTest.js, lambdas/getSunriseSunset.mjs, lambdas/sendEmail.mjs, lambdas/sendWelcomeEmail.mjs
Takes in name and email to send welcome email. Small fixes to previous lambdas are also included.
#80
=> feat: Send welcome email

src/components/History/index.tsx
=> fix: Update uid to id on history page

pnpm-lock.yaml, src/components/Profile/SignUp.tsx
Add GET request to send emails on sign up.
#81
=> feat: Add GET request to send email

.github/workflows/pr.yml, lambdas/sendDailyEmails/index.mjs
=> fix: Update env variable name in daily email function

sprint_reflections/sprint3/kbae1.commits.txt, sprint_reflections/sprint3/kbae1.md
=> feat: Kaylee sprint 3

sprint_reflections/sprint3/spaladu1.commits.txt, sprint_reflections/sprint3/spaladu1.md
=> feat: Valli sprint 3 reflection

sprint_reflections/sprint3/rpate112.commits.txt, sprint_reflections/sprint3/rpate112.md
=> feat: Add sprint 3 reflection

sprint_reflections/sprint3/tpatel25.commits.txt, sprint_reflections/sprint3/tpatel25.md
=> feat: Sprint 3 reflection

.eslintrc.js, src/components/Home/index.tsx, src/components/Profile/SignUp.tsx, src/server/emails.ts, src/server/index.ts, src/server/sunrise-sunset-time.ts
Moves welcome email into own file
Moves sunrise fetching into own file and minor refactoring to the code there.
#120
=> feat: Extract email and sunrise functions into own file

lambdas/sendDataEmail/index.mjs, lambdas/sendDataEmail/package-lock.json, lambdas/sendDataEmail/package.json, src/components/Profile/AuthorizedProfile.tsx, src/server/emails.ts
Create end point that fetches history data
#131
=> feat: Create lambda function to fetch history data from firestore

lambdas/sendDailyEmails/index.mjs, lambdas/sendWelcomeEmail.mjs
Update the styling of emails and sort times
#121
=> feat: Update email styling to match the app

src/server/emails.ts
=> chore: Fix variable names

.eslintrc.js, src/server/emails.ts, src/server/sunrise-sunset-time.ts
Console.error results in an error showing on the frontend, which is really bad
=> feat: Remove console.errors

lambdas/sendDataEmail/index.mjs
=> feat: Only fetch history for the current month

lambdas/sendDataEmail/index.mjs, src/components/Profile/AuthorizedProfile.tsx, src/server/emails.ts
=> feat: Pass email into lambda

src/components/History/index.tsx
=> fix: Set current habit when entering the history page

package.json, pnpm-lock.yaml, src/components/Profile/AuthorizedProfile.tsx, src/components/Profile/ResetLocation.tsx, src/components/Profile/index.tsx
A new way to reset your location! 
When you press the Reset Your Location button, it should set a pin at your device's location. If the device isn't sharing location, the pin will be set at the user's stored location. If the user does not have a stored location, it will default to UTK's location. 
Make sure to pnpm install before you pnpm start!!!
#123
=> feat: map-based location picker

lambdas/sendDataEmail/index.mjs
Sends an email when the user requests to get habit history.
#87
=> feat: Send habit email

sprint_reflections/sprint4/spaladu1.commits.txt
=> feat: Valli sprint 4 commits file

sprint_reflections/sprint4/ahuang16.commits.txt
=> feat: add Amy's commits text file

sprint_reflections/sprint4/rpate112.commits.txt
=> feat: Add sprint 4 commits

sprint_reflections/sprint4/kbae1.commits.txt
=> feat: Commits file
